version: 2
updates:
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: daily
    commit-message:
      prefix: 'bump'

  - package-ecosystem: nix
    directory: '/'
    schedule:
      interval: daily
    commit-message:
      prefix: 'bump'
