pull_request_rules:
  - name: Automatic merge
    description: Merge when PR passes all branch protection and has label merge-queue
    conditions:
      - or:
          - label = merge-queue
          - label = dependencies
      - check-success=All Garnix checks
    actions:
      update:
      merge:
        method: squash
