pull_request_rules:
  - name: Automatic merge
    description: Merge when PR passes all branch protection and has label merge-queue
    conditions:
      - label = merge-queue
      - check-success=All Garnix checks
    actions:
      update:
      merge:
        method: squash
merge_protections:
  - name: Enforce conventional commit
    description: Make sure that we follow https://www.conventionalcommits.org/en/v1.0.0/
    if:
      - base = master
    success_conditions:
      - "title ~= ^(fix|feat|docs|style|refactor|perf|test|build|ci|chore|revert|bump)(?:\\(.+\\))?:"
