keys:
  - &desktop age1gklefcuzv2ard7fzqkycmx8lrrscjp942xpfx2u9m0fwapt383ysnxh2qy
  - &server age1972wm0vc96w489jfw7sd335ayz4t2j4839s8sgjpdcf89fur7qfqea8lm7
creation_rules:
  - path_regex: ^hosts/desktop/secrets\.yaml$
    key_groups:
      - age:
          - *desktop
  - path_regex: ^hosts/server/secrets\.yaml$
    key_groups:
      - age:
          - *server
  - path_regex: ^modules/network'/config\.dae$
    key_groups:
      - age:
          - *desktop
  - path_regex: ^modules/boot'/db\.(key|pem)$
    key_groups:
      - age:
          - *desktop
