keys:
  - &desktop age16uursap4jrnalgpjggu38xujvtmfuvtedk8t0ksth4u5apr2wpssu5xdnh
  - &server age1972wm0vc96w489jfw7sd335ayz4t2j4839s8sgjpdcf89fur7qfqea8lm7
creation_rules:
  - path_regex: ^hosts/desktop/secrets\.yaml$
    key_groups:
      - age:
          - *desktop
  - path_regex: ^hosts/server/secrets\.yaml$
    key_groups:
      - age:
          - *server
  - path_regex: ^secrets/db\.(key|pem)$
    key_groups:
      - age:
          - *desktop
