keys:
  - &desktop age1fqsveefjf02dy9uzg2xa0pqjsaypa9d9xvpe9c293cg0cv3m7e7ss2uct5
  - &server age1nyrum2l87ktpvewhe9stjd5lfx0ghf5la5h0typ3flwaqkyk9gdqm2pws3
creation_rules:
  - path_regex: hosts/desktop/[^/]+\.yaml
    key_groups:
      - age:
          - *desktop
