keys:
  - &laptop age1h0w3eg0ac5k8jn8527qfext3sd8c44qshnpe9p7gw5zfke2glapqxa4sxq
  - &server age13lrux9jl6fphdcljc6q28wrcu89c7fjjxfnjn9qv567rxk6249xqdtfk7w
creation_rules:
  - path_regex: ^hosts/laptop/secrets\.yaml$
    key_groups:
      - age:
          - *laptop
  - path_regex: ^hosts/server/secrets\.yaml$
    key_groups:
      - age:
          - *server
