keys:
  - &recover age1fqsveefjf02dy9uzg2xa0pqjsaypa9d9xvpe9c293cg0cv3m7e7ss2uct5
  - &desktop age1csgj89yftc8587lp00m7g75khsfpzwyjytqln47x473zug4lhsfqqpsclh
  - &server age1972wm0vc96w489jfw7sd335ayz4t2j4839s8sgjpdcf89fur7qfqea8lm7
creation_rules:
  - path_regex: ^hosts/desktop/secrets\.yaml$
    key_groups:
      - age:
          - *desktop
          - *recover
  - path_regex: ^hosts/server/secrets\.yaml$
    key_groups:
      - age:
          - *server
          - *recover
