name: Build Check
on:
  pull_request:
  push:
    branches: [master]

jobs:
  tests:
    name: build ${{ matrix.name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: laptop
            attr: nixosConfigurations.laptop.config.system.build.toplevel
          - name: server
            attr: nixosConfigurations.server.config.system.build.toplevel
          - name: minimal
            attr: nixosConfigurations.minimal.config.system.build.toplevel
          - name: devShell
            attr: devShells.x86_64-linux.default
    steps:
      - uses: actions/checkout@v7
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v23
      - uses: cachix/cachix-action@v17
        with:
          name: fufu
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - uses: DeterminateSystems/magic-nix-cache-action@v15
      - name: Build ${{ matrix.name }}
        run: nix build --print-build-logs .#${{ matrix.attr }}
