name: update-flake-lock
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
permissions:
  pull-requests: write
  contents: write
jobs:
  lockfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2
      - name: Install nix
        uses: DeterminateSystems/nix-installer-action@v17
        with:
          extra-conf: |
            extra-substituters = https://cache.garnix.io
            extra-trusted-public-keys = cache.garnix.io:CTFPyKSLcx5RMJKfLo5EEPUObbA78b0YQ2DTCJXqr9g=
      - name: Check Nix flake inputs
        uses: DeterminateSystems/flake-checker-action@v10
      - name: Update flake.lock
        uses: DeterminateSystems/update-flake-lock@v26
        with:
          commit-msg: 'bump(lock): update flake.lock'
          pr-title: 'bump(lock): Update flake.lock'
          pr-labels: merge-queue
          pr-body: |
            Automated changes by GitHub Action.

            ```
            {{ env.GIT_COMMIT_MESSAGE }}
            ```
