name: update-flake-lock
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
permissions:
  pull-requests: write
  contents: write
jobs:
  lockfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.1
      - name: Install nix
        uses: DeterminateSystems/nix-installer-action@14
        with:
          extra-conf: |
            extra-substituters = https://cache.garnix.io
            extra-trusted-public-keys = cache.garnix.io:CTFPyKSLcx5RMJKfLo5EEPUObbA78b0YQ2DTCJXqr9g=
      - name: Use nix cache
        uses: DeterminateSystems/magic-nix-cache-action@v8
      - name: Update flake.lock
        uses: DeterminateSystems/update-flake-lock@v24
        with:
          commit-msg: "bump(lock): update flake.lock"
          sign-commits: true
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY  }}
          pr-title: "bump(lock): Update flake.lock"
          pr-labels: merge-queue
          pr-body: |
            Automated changes by GitHub Action.

            ```
            {{ env.GIT_COMMIT_MESSAGE }}
            ```
